# Minecraft + Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
wthit_version=8.21.1
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
# Mappings
mapping_channel=official
mapping_version=1.20.1
# Mod
mod_id=tnts
mod_name=TNTs Locos
mod_license=MIT
mod_version=1.10.12
mod_group_id=com.tnts
mod_authors=Codebuff
mod_description=38 bloques explosivos con efectos unicos (incluido el Rey TNT, un jefe que vive en el bunker), sonidos de estudio CC0, Detonador Remoto, Lanzador, Flecha, Granada, armadura de TNT completa (casco, peto, pantalon y botas con set bonus), espada, escudo y corona del Rey (con modelo 3D en el jugador), Manual de TNTs, disco de musica, aldeano Experto en TNTs, advancements, config editable por TNT (poder, fuego, mecha, activada/desactivada y calidad de particulas), texturas y modelos estilo vanilla. Se encienden con mechero, redstone o en cadena, y se pueden desactivar con tijeras.
