# Minecraft + Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
wthit_version=8.21.1
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
# Mappings
mapping_channel=official
mapping_version=1.20.1
# Mod
mod_id=tnts
mod_name=TNTs Locos
mod_license=MIT
mod_version=1.9.6
mod_group_id=com.tnts
mod_authors=Codebuff
mod_description=27 bloques explosivos (26 TNTs + mina trampa) que NO se mueven al encenderse, efectos unicos, sonidos propios, Detonador Remoto, Lanzador, Flecha y Granada de TNT, advancements, config editable, texturas y modelos estilo vanilla y animaciones de mecha. Se encienden con mechero, redstone o en cadena.
